blank_issues_enabled: false
contact_links:
  - name: Are there any issues you're experiencing with Swiftwave? 
    url: https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q
    about: Join us on Slack to meet members, contributors and the maintainer and brainstorm ideas.