name: ⚒️ Installation Issue
description: Having trouble installing Swiftwave? Ask here!
title: "Installation Issue"
labels: ["⚒️ installation", "open", "pending"]
body:
- type: dropdown
  id: installation_environment_type
  attributes:
    label: Installation Environment
    description: In which mode are you trying to install Swiftwave?
    options:
      - 'Development Setup'
      - 'Production deployment'
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the issue you are facing?
    description: Provide a detailed description of your issue
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: |
      If applicable, add screenshots to help explain your problem

      Tip: You can attach images or videos by clicking this area to highlight it and then dragging files in
  validations:
    required: false
- type: textarea
  attributes:
    label: Device Information [optional]
    description: |
      examples:
        - **OS**: Ubuntu 22.04
        - **Browser**: chrome
        - **Swiftwave version**: latest
        - **Docker version**: 24.0.2
    value: |
        - OS:
        - Browser:
        - Swiftwave version:
        - Docker version:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Stack Trace [optional]
    description: If you have a stack trace for the error paste it here
  validations:
    required: false