name: Deploy to Server
on:
  workflow_dispatch:

jobs:
  build-production:
    permissions:
      contents: read
      packages: write
    uses: swiftwave-org/SwiftWave/.github/workflows/docker-publish.yml@main

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
    
      - name: SSH to remote server and execute
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ~ && export ENVIRONMENT=staging
            ls -l /dev/
            curl -L get.swiftwave.org | bash
