name: Deploy to Server
on:
  workflow_dispatch:
  schedule:
    - cron: '* */3 * * *'
  push:
    branches: [ "main" ]

jobs:
  build-production:
    permissions:
      contents: read
      packages: write
    uses: swiftwave-org/SwiftWave/.github/workflows/docker-publish.yml@main

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Delete all cachae
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/lib/docker/*
      - name: Reinstall Swiftwave
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ~ 
            curl -L get.swiftwave.org | ENVIRONMENT=staging bash
